### ISSUE TITLE
[BUG] - Tags de emojis em markdown estão aparecendo no novo git pages

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#131]
**Descreva o bug**
Várias tags de emojis em markdown ```Ex.: isso é um emoji: :abc: ``` estão aparecendo em sua forma textual no novo git pages.
 

**Passo a passo para a reprodução do bug**
Para reproduzir o bug, siga os passos:
1. Vá até o [novo git pages](https://fga-eps-mds.github.io/2021.2-INDICAA-Wiki/).
2. Clique em contribuição
3. Clique em Template de commit
4. Role a página
5. Veja o bug

**Comportamento esperado**
O comportamento esperado é de que os emojis aparecessem da seguinte forma: 🚀 💾 🌟 

**Screenshots**
![image](https://user-images.githubusercontent.com/62526025/163249406-d88c9d4f-a06f-41ae-9f4b-c526a2ae1dd5.png)

**Comment by guibrbs** [comment]
O bug foi identificado, e seguirá para a correção.
Para corrigir, adicionaremos o seguinte trecho de código que insere dentro do mkdocs a leitura dos emojis, reproduzindo-os no navegador conforme o esperado, além de atribuir os arquivos markdown em HTML.
```
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
```
